FROM python:3.10

RUN pip install --upgrade pip poetry

WORKDIR /code
COPY pyproject.toml poetry.lock ./

RUN poetry install

CMD ["poetry", "run", "flask", "--app", "backend/app", "--debug", "run", "--host", "0.0.0.0", "--port", "3000"]
