name: Linting
on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull base images
        run: docker-compose pull
      - name: Start the containers
        run: scripts/ci-start.sh
      - name: Flake8
        run: docker-compose exec -T backend poetry run flake8
